name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build project
        run: npm run build

      # Start the application
      - name: Start application
        run: npm start &

      # Run Cypress tests with Mochawesome reporter
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: http://localhost:3000
          wait-on-timeout: 60
          command: npm run cy:run

      # Merge Mochawesome reports
      - name: Merge Mochawesome reports
        run: npx mochawesome-merge cypress/results/*.json > cypress/results/mochawesome.json

      # Generate Mochawesome HTML report
      - name: Generate Mochawesome HTML report
        run: npx mochawesome-report-generator cypress/results/mochawesome.json -o cypress/results/

      # Upload test reports
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-reports
          path: cypress/results/*.html